[build]
    publish = "dist"
    command = "npm run build"
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    force = true
    conditions = { header = {"Accept" = ["text/html"]}}
